const tagsList = {
  Spirits: [
    'Gin',
    'Vodka',
    'Rum',
    'Dark Rum',
    'Light Rum',
    'Scotch',
    'Tequila',
    'Bourbon',
    'Brandy',
    'Cognac',
    '151 Proof Rum',
  ],
  Liqueurs: [
    'Triple Sec',
    'Blue Curacao',
    'Malibu Rum',
    'Midori melon liqueur',
    'Chambord raspberry liqueur',
    'Aperol',
    'Sambuca',
    'Campari',
    'Galliano',
    'Green Chartreuse',
    'Absinthe',
    'Jägermeister',
    'Kahlua',
    'Amaretto',
  ],
  Wines: [
    'Red Wine',
    'Prosecco',
    'Champagne',
    'Dry Vermouth',
    'Sweet Vermouth',
  ],
  Mixers: [
    'Soda Water',
    'Tonic Water',
    'Cranberry Juice',
    'Pineapple Juice',
    'Orange Juice',
    'Ginger Ale',
    'Lemonade',
    'Coca-Cola',
  ],
  Others: [
    'Bitters',
    'Grenadine',
    'Cream',
    'Lemon Juice',
    'Lemon',
    'Orange',
    'Lime',
    'Lime Juice',
    'Egg White',
    'Egg',
    'Honey',
    'Maraschino Cherry',
    'Mint',
    'Pineapple',
    'Sugar',
    'Elderflower cordial',
    'Milk',
  ],
};

export default tagsList;
